version: 2.1
jobs:
  build:
    docker:
      # new standalone docker container
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      # PBRP_BRANCH: 'devs'
      VERSION: '2.9.1'
      MAINTAINER: 'koumaza'
      VENDOR: 'motorola'
      CODENAME: 'payton'
      BUILD_LUNCH: 'omni_payton-eng'
      TEST_BUILD: 'true'
      # PB_OFFICIAL: 'true'
      CHANGELOG: " - Last source TeamWin 3.4.0\n
	- Improve touch\n
	- Miscellaneous"

      # EXTRA_CMD: # some required commands like `ls` after `repo sync`, write in single line
    working_directory: /home/builder/pitchblack # '/home/builder/' will also work just fine
    steps:
      - checkout
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/koumaza/android_device_motorola_payton-1/android-9.0/build.sh
            source build.sh
